add spatial clustering category
spatial-data-lab/knime-geospatial-extension pull request #179
Opened 2023-03-17 13:18 UTC by UrbanGISer

Please help to view the new category nodes

2023-03-28 15:09 UTC, koettert commented
@UrbanGISer please add the used libraries to the environment file with the used versions

2023-08-11 14:53 UTC, koettert commented
@UrbanGISer I rebased the branch and added the new py file to the extension to include the nodes into the node repository: https://github.com/spatial-data-lab/knime-geospatial-extension/pull/179/commits/fa4d696d47e880799bb0f8929928b8262040d819

I also added several comments. Can you please address them.

2023-08-11 14:54 UTC, koettert requested changes

2023-08-29 02:01 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    description="Output table with Mean center and standard distance .",
revised

2023-08-29 02:06 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf = gp.GeoDataFrame(input_1.to_pandas(), geometry=self.geo_col)
gdf = knut.load_geo_data_frame(input_1, self.point_geo_col, exec_context)

2023-08-29 02:07 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return knext.Table.from_pandas(mcgdf)
return knut.to_table(mcgdf, exec_context)

2023-08-29 02:09 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +            {"x": [mc[0]], "y": [mc[1]]},
revised

2023-08-29 02:09 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        mcgdf["std_distance"] = pointpats.std_distance(pp.points)
mcgdf["Distance"] = pointpats.std_distance(pp.points)

2023-08-29 02:14 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    description="Geodata from the input file path.",
Table with geometry column for computing standard deviational ellipse.

2023-08-29 02:15 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    This node use the Pysal package [pointpats](https://pointpats.readthedocs.io/en/master/api.html)
revised

2023-08-29 02:18 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    geo_col = knext.ColumnParameter(
geo_col = knut.geo_col_parameter(
        description="Select the geometry column to compute standard deviational ellipse."
    )

2023-08-29 02:19 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    geo_col = knext.ColumnParameter(
geo_col = knut.geo_col_parameter(
        description="Select the geometry column to compute mean center and standard distance."
    )

2023-08-29 02:29 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return None
_COL_GEOMETRY = "geometry"
    
    def configure(self, configure_context, input_schema):
        self.geo_col = knut.column_exists_or_preset(
            configure_context, self.geo_col, input_schema, knut.is_geo
        )
        return knext.Schema(knut.TYPE_POLYGON, self._COL_GEOMETRY)

2023-08-29 02:32 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return knext.Table.from_pandas(gdf)
return knut.to_table(gdf, exec_context)

2023-08-29 02:33 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf = gp.GeoDataFrame(input_1.to_pandas(), geometry=self.geo_col)
gdf = knut.load_geo_data_frame(input_1, self.geo_col, exec_context)

2023-08-29 02:34 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    description="Geodata from the input file path.",
revised：Geodata for spatial clustering implementation.

2023-08-29 02:35 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    This node use the Pysal package [pointpats](https://pointpats.readthedocs.io/en/master/api.html)
revised

2023-08-29 02:36 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    to  calculate parameters of standard deviational ellipse for a point pattern, which is a common way of measuring
revised

2023-08-29 02:38 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    The Spatial C(K)luster Analysis by Tree Edge Removal(SKATER) algorithm introduced by Assuncao et al. (2006)
added

2023-08-29 02:38 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    It provides an optimized algorithm to prune to tree into several clusters that their values of selected variables are as similar as possible.
revised

2023-08-29 02:40 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    geo_col = knext.ColumnParameter(
revised：   geo_col = knut.geo_col_parameter(
        description="Select the geometry column to implement spatial clustering."
    )

2023-08-29 02:45 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    cluster_k = knext.IntParameter(
added

2023-08-29 02:50 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf = gp.GeoDataFrame(input_1.to_pandas(), geometry=self.geo_col)
revised

2023-08-29 02:50 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return knext.Table.from_pandas(gdf)
revised

2023-08-29 02:51 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Spatial Weight model",
revised

2023-08-29 02:52 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Attribute columns for Clustering",
revised

2023-08-29 02:52 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "The Number of user-defined clusters.",
revised

2023-08-29 14:20 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf["clusterid"] = skatercluster["Clusters"]
# Common used column names
_COL_CLUSTER = "Cluster ID"

return input_schema.append(knext.Column(knext.int64(), _COL_CLUSTER))

2023-08-29 14:21 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return None
return input_schema.append(knext.Column(knext.int64(), _COL_CLUSTER))

2023-08-29 14:22 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    geo_col = knext.ColumnParameter(
geo_col = knut.geo_col_parameter(
        description="Select the geometry column to implement spatial clustering."
    )

2023-08-30 08:29 UTC, koettert commented
@UrbanGISer unfortunately the Python framework as of now doe snot support array parameter. So we need to make due with the workaround of using a comma separated list. Internal ticket number for array parameter is AP-20920 and they will be supported at the end of the year at the earliest.

2023-09-04 18:49 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "A minimum value that the sum value of bounding variable in each cluster should be greater than.",
reivsed

2023-09-04 18:51 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    It is developed by D. Guo (2008). Like SKATER, REDCAP starts from building a spanning tree with
revised

2023-09-04 18:53 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "A minimum value that the sum value of bounding variable in each cluster should be greater than.",
revised

2023-09-04 18:53 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Spatial Weight model",
revised

2023-09-04 19:17 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        enum=[
class LinkageModes(knext.EnumParameterOptions):
        FIRST_SINGLE = (
            "firsorder-singlelinkage",
            """First-order and Single-linkage. In this local approach, clusters are formed by considering only immediate neighbors, 
            and their distance is measured by the shortest distance between any pair of points from each cluster.""",
        )
        FULL_SINGLE = (
            "fullorder-singlelinkage",
            """Full-order and Single-linkage. Using a global context, this approach considers all points in the dataset for clustering 
            and measures the distance between clusters as the shortest distance between any pair of points from each cluster.""",
        )
        FULL_COMPLETE = (
            "fullorder-completelinkage",
            """Full-order and Average-linkage. This method also considers all points in the dataset for clustering and calculates 
            the distance between clusters as the average distance between all pairs of points, one from each cluster.""",
        )
        FULL_AVERAGE = (
            "fullorder-averagelinkage",
            """Full-order and Average-linkage. This method also considers all points in the dataset for clustering and calculates 
            the distance between clusters as the average distance between all pairs of points, one from each cluster.""",
        )
        FULL_WARD = (
            "fullorder-wardlinkage",
            """Full-order and Wards-linkage.  All points in the dataset are considered for clustering, and the distance 
            between clusters is calculated in a way that minimizes the internal variance within each cluster.""",
        )  

        @classmethod
        def get_default(cls):
            return cls.FULL_COMPLETE

    link_mode  = knext.EnumParameter(
        label="Linkage model",
        description="Input linkage mode.",
        default_value=LinkageModes.get_default().name,
        enum=LinkageModes,
    )

2023-09-04 19:21 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf["clusterid"] = final_cluster["Clusters"]
gdf[_CLUSTER_ID] = final_cluster["Clusters"]

2023-09-04 19:37 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return None
def configure(self, configure_context, input_schema):
        self.geo_col = knut.column_exists_or_preset(
            configure_context, self.geo_col, input_schema, knut.is_geo
        )
        return input_schema.append(knext.Column( knext.int64(), name=_CLUSTER_ID))

2023-09-04 19:41 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf = gp.GeoDataFrame(input_1.to_pandas(), geometry=self.geo_col)
gdf0 = knut.load_geo_data_frame(input_1, self.geo_col, exec_context)

2023-09-04 19:43 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return knext.Table.from_pandas(gdf)
knut.to_table(gdf, exec_context)

2023-09-04 19:43 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "isolate column from MSSC",
revised

2023-09-04 20:14 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    description="Geodata from the input file path.",
revisedd

2023-09-04 20:15 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Attribute columns for Clustering",
revised

2023-09-04 23:20 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    constraint_list = knext.StringParameter(
attribute_list = knext.MultiColumnParameter(
        "Attribute columns for clustering",
        "Select columns for calculating attribute distance.",
        port_index=0,
        column_filter=knut.is_numeric,
    )

2023-09-04 23:22 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return knext.Table.from_pandas(gdf0)
revised

2023-09-04 23:23 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Attribute columns for Clustering",
revised

2023-09-04 23:23 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Attribute columns for Clustering",
revised

2023-09-04 23:25 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +     - ward
revised

2023-09-04 23:25 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "A minimum value that the sum value of bounding variable in each cluster should be greater than.",
revised

2023-09-04 23:33 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        enum=[
revised

2023-09-04 23:33 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return None
revised

2023-09-04 23:36 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    The so-called max-p regions model (outlined in Duque, Anselin, and Rey 2012)
added

2023-09-04 23:38 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    description="Output table with peano curve spatal order.",
revised

2023-09-04 23:38 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        return None
revised

2023-09-04 23:39 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf["theid"] = np.arange(gdf.shape[0]).tolist()
it is a intermediate one , so that should be fine

2023-09-04 23:39 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf["peanoorder"] = 0
_PEANO_CURVE_ORDER = "Peano Order"

2023-09-04 23:42 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Binary-digit scale",
"Binary-digit scale or as powers of 2",

2023-09-04 23:45 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        "Select the column 'isoloate'generated by MSSC clustering.",
revised

2023-09-04 23:46 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    name="Isolation Tackler",
It can be applied to other clustering result

2023-09-04 23:47 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    description="Geodata from the clustering.",
See above, other clustering result might be used as well

2023-09-11 21:26 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    minibound = knext.DoubleParameter(
k = knut.ensure_value2(self.cluster_k,1)

2023-09-11 21:28 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    grid_k = knext.IntParameter(
k = knut.ensure_value2(self.cluster_k,1)

2023-09-11 21:29 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        gdf0 = gp.GeoDataFrame(input_1.to_pandas(), geometry=self.geo_col)
Solved

2023-09-11 21:30 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    The MSSC model (Mu and Wang 2008) follows the values of spatial order along the Peano curve with breaking points that are defined by a threshold population size.
added

2023-09-11 21:49 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        )
self.clusterid_col = knut.column_exists_or_preset(
            configure_context, _CLUSTER_ID, input_schema, knut.is_long
        )
        self.clusterid_col = knut.column_exists_or_preset(
            configure_context, _ISOLATED, input_schema, knut.is_long
        )

2023-09-11 22:26 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        ConstraintList = self.constraint_list.split(";")
they are from my previous code for ArcGIS Pro, I revise most of  the variables

2023-09-11 22:29 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +    The node forces a cluster membership for unclaimed or loose-end units, especially useful for the enclave units in Mixed level regionalization model.
It mainly works fo MSSC, but if some input shares the same structure, that might be applicable as well

2023-09-11 22:34 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        )
self.clusterid_col = knut.column_exists_or_preset(
            configure_context, _CLUSTER_ID, input_schema, knut.is_long
        )
        self.isolate_col = knut.column_exists_or_preset(
            configure_context, _ISOLATED, input_schema, knut.is_long
        )

2023-09-11 22:56 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +            for index, rowLocal in df2.iterrows():
for i in range(isoCount1):
            process_counter = i + 1
            exec_context.set_progress(
                0.8 * process_counter / isoCount1,
                f"Batch {process_counter} of {isoCount1} processed",
            )
            knut.check_canceled(exec_context)

2023-09-11 22:56 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +        for index, row in lyrIso.iterrows():
exec_context.set_progress(
                    0.8 * rowCount / n_loop,
                    f"Batch {rowCount} of {n_loop} processed",
                )

                knut.check_canceled(exec_context)

2023-09-11 22:57 UTC, UrbanGISer commented on knime_extension/src/nodes/spatialclustering.py
> +# SKATER
we can come back to this after release

2023-09-13 12:50 UTC, merged