add MAEP node
spatial-data-lab/knime-geospatial-extension pull request #182
Opened 2023-03-17 16:54 UTC by UrbanGISer

add MAEP node in location analysis

2023-09-12 15:04 UTC, koettert requested changes

2023-09-13 21:35 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +    description="""The table MUST contain m rows and (k+1) columns,
added

2023-09-13 21:35 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +    description="candidate column name and chosen status(1/0)",
revised

2023-09-13 21:35 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +    short_description="maximal accessibility equality problem (MAEP)",
revised

2023-09-13 21:39 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +    description="""The optimization objective of MAEP is to minimize inequality in accessibility of facilities
added

2023-09-13 21:46 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +    Newcapacity = knext.DoubleParameter(
revised

2023-09-13 23:01 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        "New resource or capacility for facilities .",
revised

2023-09-13 23:01 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        "The column for demand(e.g.,population). ",
revised

2023-09-13 23:02 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        "Travel cost column of  required facility or Travel cost column of nearest required facilities. ",
revised

2023-09-13 23:02 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +                knext.Column(knext.string(), "FacilityID"),
revised

2023-09-13 23:02 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        D = df1[self.Demand]
revised

2023-09-13 23:04 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        return knext.Schema.from_columns(
they can not be preset

2023-09-14 09:02 UTC, koettert requested changes
Please upload a test workflow for the node to the KNIME Hub otherwise I cannot test it.

2023-09-14 12:29 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +    Decaymodel = knext.StringParameter(
revised

2023-09-14 12:29 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        df1 = gp.GeoDataFrame(input_1.to_pandas()).reset_index(drop=True)
revised

2023-09-14 12:41 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +    name="Input tabale for demand and new facilities",
revised

2023-09-14 14:37 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        dfn1 = gp.GeoDataFrame(input_1.to_pandas()).reset_index(drop=True)
same as the previous location analysis node,  the data can use geo or non-geo data

2023-09-14 14:37 UTC, UrbanGISer commented on knime_extension/src/nodes/locationanalysis.py
> +        dfn1 = gp.GeoDataFrame(input_1.to_pandas()).reset_index(drop=True)
Is there any other way to import the data

2023-09-15 11:35 UTC, closed without merging

2023-09-15 11:35 UTC, koettert commented
Changes were integrated into the other branch and merged to main