Add ip to geometry node
spatial-data-lab/knime-geospatial-extension pull request #261
Opened 2023-07-14 15:27 UTC by wybert

Added the ip to the geometry node, may need server thing to be done

- [ ] input schema
- [ ] add more options
- [ ] Keep column name unique
- [ ] limit the column name if needed? Now I append the city, region, country, long,lat, and geometry columns

2023-07-14 15:29 UTC, wybert commented
This could solve this issue #41

2023-07-14 16:27 UTC, wybert commented
Notice a Python package called [ip2geotools](https://github.com/tomas-net/ip2geotools) for various services for free and commercial providers. But it seems that it haven't been update recently.

2023-08-15 15:17 UTC, koettert commented
@UrbanGISer can you please create a beautiful icon for this new node

2023-08-31 09:52 UTC, koettert requested changes
Please review my changes and add the missing icon. Once done you can merge to master.

2023-08-31 09:52 UTC, koettert commented on knime_extension/src/nodes/conversion.py
> +    icon_path=__NODE_ICON_PATH + "IPToGeo.png",
@wybert can you please also include the node icon into the pull request

2023-09-05 14:49 UTC, koettert commented
Please add the missing icon and merge the pull request if you are happy with my changes @wybert

2023-09-06 21:04 UTC, wybert commented
> 

@UrbanGISer I need your help to add an AWESOME icon

2023-09-07 20:35 UTC, wybert commented
@koettert Lingbo added an icon for this, you could merge the pr now:)

2023-09-07 21:54 UTC, merged