add more data nodes
spatial-data-lab/knime-geospatial-extension pull request #312
Opened 2023-11-27 22:31 UTC by wybert

This will solve #308

2024-02-06 15:59 UTC, koettert commented
@koettert test that the data nodes especially the ESRI node also runs on Linux!

2024-02-11 15:22 UTC, koettert requested changes
I contacted our legal department to make sure that we are allowed to integrate the sources and under which terms. We need to make sure that we are allowed to include these sources into the AP.

2024-02-11 15:22 UTC, koettert commented on knime_extension/src/nodes/opendata.py
> +        kws = {"url": url, "timeout": 120}
Expose timeout as advanced parameter

2024-02-11 15:22 UTC, koettert commented on knime_extension/src/nodes/opendata.py
> +        response = requests.get(url, timeout=120)
Expose timeout as advanced parameter

2024-03-18 13:24 UTC, koettert commented
@wybert when I use the geospatial_env.yml file of this PR I can no longer resolve my Python envrionment. It seems that it contains conflicting version.

2024-03-18 13:27 UTC, koettert commented
Results from our legal department:
- Add a copyright notice similar to the OSM nodes to the GDelt node according to https://www.gdeltproject.org/about.html#termsofuse
- Remove the DataCenter node since it has no clear licensing
- For the Esri nodes we need to clearly show the copyright notice for each item in the KNIME table

2024-03-26 15:18 UTC, wybert commented
> @wybert when I use the geospatial_env.yml file of this PR I can no longer resolve my Python envrionment. It seems that it contains conflicting version.

It got stuck in my Windows machine when creating a new environment.

2024-04-08 14:01 UTC, koettert commented
![image](https://github.com/spatial-data-lab/knime-geospatial-extension/assets/11409922/aa87619f-387e-4187-bef4-42ce8542c598)
Not sure if downgrading osmnx from version 1.7 (which we ship right now) to 1.2.2. What do you think?

2024-04-09 15:00 UTC, koettert commented
To avoid dependency conflicts we will move the ESRI nodes out of the general Geospatial extension into a dedicated ESRI extension which can be installed separately. This extension would start to only provide the data nodes but could in the future be extended to provide nodes for more advanced and potentially commercial ArcGis features

2024-05-07 14:49 UTC, koettert commented
@wybert please add a copyright notice similar to the OSM nodes to the GDelt node according to https://www.gdeltproject.org/about.html#termsofuse

2024-05-21 14:36 UTC, koettert requested changes

2024-05-21 14:36 UTC, koettert commented on knime_extension/geospatial_env.yml
> +  - esri
@wybert please remove the dependency and once done assign to me

2024-08-19 15:57 UTC, merged